[versions]
agp = "9.4.0"
androidx-annotation = "1.10.0"
androidx-appcompat = "1.8.0"
androidx-collection = "1.6.0"
androidx-core-ktx = "1.19.0"
androidx-core-splashscreen = "1.2.0"
androidx-lifecycle = "2.11.0"
androidx-media = "1.8.0"
androidx-preference-ktx = "1.2.1"
androidx-swiperefreshlayout = "1.2.0"
androidx-test-espresso = "3.7.0"
androidx-test-ext-junit = "1.3.0"
androidx-test-ext-junit-ktx = "1.3.0"
androidx-test-rules = "1.7.0"
assertj = "3.27.7"
google-material = "1.14.0"
hamcrest = "3.0"
jacoco = "0.8.15"
junit = "4.13.2"
junit-toolbox = "2.4"
kotlin = "2.4.20"
kotlinx-coroutines = "1.11.0"
ktlint = "14.2.0"
mockito-core = "5.23.0"
mockito-kotlin = "6.3.0"
robolectric = "4.17"
slf4j-simple = "2.0.19"
vico-views = "3.2.3"

[libraries]
# Dependencies
androidx-annotation = { group = "androidx.annotation", name = "annotation", version.ref = "androidx-annotation" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidx-appcompat" }
androidx-collection-ktx = { group = "androidx.collection", name = "collection-ktx", version.ref = "androidx-collection" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidx-core-ktx" }
androidx-core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "androidx-core-splashscreen" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle" }
androidx-media = { group = "androidx.media", name = "media", version.ref = "androidx-media" }
androidx-preference-ktx = { group = "androidx.preference", name = "preference-ktx", version.ref = "androidx-preference-ktx" }
androidx-swiperefreshlayout = { group = "androidx.swiperefreshlayout", name = "swiperefreshlayout", version.ref = "androidx-swiperefreshlayout" }
google-material = { group = "com.google.android.material", name = "material", version.ref = "google-material" }
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
vico-views = { group = "com.patrykandpatrick.vico", name = "views", version.ref = "vico-views" }
# Test Dependencies
androidx-test-espresso-contrib = { group = "androidx.test.espresso", name = "espresso-contrib", version.ref = "androidx-test-espresso" }
androidx-test-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidx-test-espresso" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
androidx-test-ext-junit-ktx = { group = "androidx.test.ext", name = "junit-ktx", version.ref = "androidx-test-ext-junit-ktx" }
androidx-test-rules = { group = "androidx.test", name = "rules", version.ref = "androidx-test-rules" }
assertj-core = { group = "org.assertj", name = "assertj-core", version.ref = "assertj" }
hamcrest = { group = "org.hamcrest", name = "hamcrest", version.ref = "hamcrest" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
junit-toolbox = { group = "com.googlecode.junit-toolbox", name = "junit-toolbox", version.ref = "junit-toolbox" }
kotlin-test = { group = "org.jetbrains.kotlin", name = "kotlin-test", version.ref = "kotlin" }
kotlin-test-junit = { group = "org.jetbrains.kotlin", name = "kotlin-test-junit", version.ref = "kotlin" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
mockito-core = { group = "org.mockito", name = "mockito-core", version.ref = "mockito-core" }
mockito-kotlin = { group = "org.mockito.kotlin", name = "mockito-kotlin", version.ref = "mockito-kotlin" }
robolectric = { group = "org.robolectric", name = "robolectric", version.ref = "robolectric" }
slf4j-simple = { group = "org.slf4j", name = "slf4j-simple", version.ref = "slf4j-simple" }
# Jacoco
jacoco-internal = { group = "org.jacoco", name = "org.jacoco.agent", version.ref = "jacoco" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-allopen = { id = "org.jetbrains.kotlin.plugin.allopen", version.ref = "kotlin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
