name: Bug report
description: Create a report to help us fix the issue
title: "[BUG] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting an issue — please fill in the fields below. Do not include passwords or other sensitive information.
  - type: input
    id: short_title
    attributes:
      label: Short title
      description: One-line summary of the bug
      placeholder: App crashes when scanning
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of the problem
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Exact steps to reproduce the behavior
      placeholder: |
        1) Open app
        2) Tap Scan
        3) Observe crash
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
  - type: textarea
    id: logs
    attributes:
      label: Relevant logs/screenshots
      description: Paste logs or add screenshots if available
  - type: dropdown
    id: reproduction_frequency
    attributes:
      label: Reproduction frequency
      options:
        - Always
        - Sometimes
        - Rarely
  - type: dropdown
    id: severity
    attributes:
      label: Severity / Impact
      options:
        - Low
        - Medium
        - High
  - type: input
    id: device_model
    attributes:
      label: Device model
      placeholder: e.g. Pixel 6, Samsung S21
  - type: input
    id: android_version
    attributes:
      label: Android version / API level
      placeholder: e.g. Android 12 (API 31)
  - type: input
    id: app_version
    attributes:
      label: WiFiAnalyzer version
      placeholder: e.g. 3.2.1
  - type: textarea
    id: additional_context
    attributes:
      label: Additional context
      description: Any other information (network setup, nearby APs, whether it occurs on other devices)
