name: Android Instrumentation Tests
on:
  push:
    branches:
      - release
    paths-ignore:
      - '**/*.md'
      - '.github/workflows/android-ci.yml'
      - '.github/workflows/codeql-analysis.yml'
      - '.github/workflows/stale.yml'
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/common-setup
      - name: Build APKs
        run: ./gradlew assembleDebug assembleAndroidTest
      - name: Upload APKs
        uses: actions/upload-artifact@v4
        with:
          name: apks
          path: |
            app/build/outputs/apk/debug/app-debug.apk
            app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk

  test:
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Download APKs
        uses: actions/download-artifact@v4
        with:
          name: apks
      - name: Run tests
        uses: emulator-wtf/run-tests@v0
        with:
          api-token: ${{ secrets.EW_API_TOKEN }}
          app: app-debug.apk
          test: app-debug-androidTest.apk
          outputs-dir: build/test-results
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          path: |
            build/test-results
            app/build/reports/androidTests
      - name: Publish test results
        uses: mikepenz/action-junit-report@v5
        if: always()
        with:
          report_paths: 'build/test-results/**/*.xml'
